// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxUOg8BOd4hOgHo9ycn9fYtw9sxaaMuuw',
    appId: '1:148970052983:web:1f07f1ad412360ea6a9572',
    messagingSenderId: '148970052983',
    projectId: 'todo2-d8a22',
    authDomain: 'todo2-d8a22.firebaseapp.com',
    storageBucket: 'todo2-d8a22.appspot.com',
    measurementId: 'G-1GVPVL3CBY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2dN4ndWxCSJXF0soDBeEbfxaORZ4CXCo',
    appId: '1:148970052983:android:d61de09b1d6d8d886a9572',
    messagingSenderId: '148970052983',
    projectId: 'todo2-d8a22',
    storageBucket: 'todo2-d8a22.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTwlPPt6BCjhc0fdj8563Zi1Mw_l-MZGY',
    appId: '1:148970052983:ios:01d5babc34fc24246a9572',
    messagingSenderId: '148970052983',
    projectId: 'todo2-d8a22',
    storageBucket: 'todo2-d8a22.appspot.com',
    iosBundleId: 'com.example.todo2app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTwlPPt6BCjhc0fdj8563Zi1Mw_l-MZGY',
    appId: '1:148970052983:ios:01d5babc34fc24246a9572',
    messagingSenderId: '148970052983',
    projectId: 'todo2-d8a22',
    storageBucket: 'todo2-d8a22.appspot.com',
    iosBundleId: 'com.example.todo2app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxUOg8BOd4hOgHo9ycn9fYtw9sxaaMuuw',
    appId: '1:148970052983:web:a8326fde0a0ba2466a9572',
    messagingSenderId: '148970052983',
    projectId: 'todo2-d8a22',
    authDomain: 'todo2-d8a22.firebaseapp.com',
    storageBucket: 'todo2-d8a22.appspot.com',
    measurementId: 'G-NCCDVKEL78',
  );
}
